version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/ABM"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/SistemaDeAparcamiento"
    schedule:
      interval: "weekly"


  - package-ecosystem: "nuget"
    directory: "/Codewars"
    schedule:
      interval: "weekly"
