name: Build NET Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Framework
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install dependencies
        run: nuget restore ABM\ABM.sln
      
      - name: Build Debug
        run: msbuild ABM\ABM.sln

      - name: Setup VSTest.exe
        run: Malcolmnixon/Setup-VSTest@v3

      - name: Testing ABM
        run: vstest.console.exe ABM\ABM.Core.UnitTests\bin\Debug\ABM.Core.UnitTests.dll

